version: "3.7"

services:

  api_service:
    container_name: api_service
    build: .
    volumes:
      - ./api_service:/src/main
    restart: always
    ports:
      - 9000:9000
    networks:
      - dockerinternalnetwork

networks:
  dockerinternalnetwork:
    driver: bridge