name: Deploy Master

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: main

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: 'Build:dockerimage'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: "RahulNenavath"
          password: ${{ secrets.ACCOUNT_PAT }}
          repository: rahulnenavath/guess-the-hero
          tags: prod
      - name: "Pull:dockerimage"
        uses: fifsky/ssh-action@master
        with:
          command: echo ${{ secrets.ACCOUNT_PAT }} | docker login ghcr.io -u RahulNenavath --password-stdin && docker image prune -f && docker pull ghcr.io/rahulnenavath/guess-the-hero && docker-compose up -d
          host: ${{ secrets.SERVER_EC2_HOSTNAME }}
          user: ${{ secrets.SERVER_EC2_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}